# Generated by Django 2.1.5 on 2022-02-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_signup_ros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='RoS',
        ),
        migrations.AddField(
            model_name='signup',
            name='isStu',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
