# Generated by Django 4.0.2 on 2022-02-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_signup_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(default='', max_length=254)),
                ('city', models.CharField(default='', max_length=30)),
                ('dob', models.DateField()),
                ('uname', models.CharField(max_length=30)),
                ('cname', models.CharField(max_length=30)),
                ('pyear', models.PositiveIntegerField(default='')),
                ('spi', models.PositiveIntegerField(default='')),
                ('pl', models.CharField(max_length=30)),
                ('description', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
