# Generated by Django 2.1.5 on 2022-03-28 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20220328_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('number', models.PositiveIntegerField(default='')),
                ('email', models.EmailField(default='', max_length=254)),
                ('details', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
