# Generated by Django 3.2.8 on 2022-04-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_contactform'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='signup',
            name='gender',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='signup',
            name='location',
            field=models.CharField(default='', max_length=115),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
